// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture

struct PositionData
{
    float3 position;
    float4 color;
};

RWStructuredBuffer<PositionData> _PositionBuffer;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!

    PositionData data;
    data.position = float3(id.x,0,id.y);
    data.color = float4(id.x/255.0f, id.y/255.0f, 0, 1);
    _PositionBuffer[id.x + id.y * 256] = data;
}
